### ISSUE TITLE
Failed to redeem RAV

### ISSUE THREAD

**Issue by suntzu93** [graphprotocol/indexer#1010]
I encountered a situation where allocations have been redeemed on-chain but in the database the 'final' column is still false. As a result, the agent attempts to redeem that allocation again and encounters the error 'Failed to redeem query fee voucher.' After checking the code, I realized a few points:

1. https://github.com/graphprotocol/indexer/blob/ade405e07dd46e30dc4e7807417974133b87f2b0/packages/indexer-common/src/allocations/query-fees.ts#L603 This code aims to find items that exist on-chain and also in the database but have 'final' = false. I think the correct approach should be `ravsLastNotFinal.find` , if you use `!ravsLastNotFinal.find`  it means that it exists on-chain but does not exist in the database, which I have never encountered. If such a case were to occur, the method `markRavAsRedeemed` would only be updating the item, if it doesn't exist in the database, how can it update?

2. I debugged and found the following data:
   - `rav.senderAddress = 0xDDE4cfFd3D9052A9cb618fC05a1Cd02be1f2F467`
   - `rav.allocationId = 0xC0ccccc865cEd16F3E56640E5798A9648233AE92`
   - `tx.sender.id = 0xdde4cffd3d9052a9cb618fc05a1cd02be1f2f467`
   - `tx.allocationID = 0xc0ccccc865ced16f3e56640e5798a9648233ae92`

https://github.com/graphprotocol/indexer/blob/ade405e07dd46e30dc4e7807417974133b87f2b0/packages/indexer-common/src/allocations/query-fees.ts#L605

   In the code, you are not using `toLowerCase()`, so clearly, this case will not be updated as redeemed even though there is a transaction on-chain.

3. https://github.com/graphprotocol/indexer/blob/ade405e07dd46e30dc4e7807417974133b87f2b0/packages/indexer-common/src/allocations/query-fees.ts#L1124 The method  `markRavAsRedeemed` has a logic error when `redeemed_at` is a timestamp, while you are using a number."

**Comment by gusinacio** [comment]
Hello @suntzu93, given your case I think that the most probable errors was because #1011, since you redeemed multiple allocations (possible more than 100) in less than 1 hour.

I'm closing this issue in favor of the other one.
