### ISSUE TITLE
Feature: use different nodes for different methods/capabilities

### ISSUE THREAD

**Issue by akme** [graphprotocol/indexer#105]
It would be nice to have the option to use different nodes for different methods/capabilities.
For example, I want to use one node only as an archive and another only for traces:
```
--ethereum-rpc "mainnet:archive:http://1.2.3.4:8545 mainnet:traces:http://5.6.7.8:8545"
```
or with ENV
```
ETHEREUM="mainnet:archive:http://1.2.3.4:8545 mainnet:traces:http://5.6.7.8:8545"
```

**Comment by fordN** [comment]
@akme  This is supported in graph-node!
