### ISSUE TITLE
Bad Gateway

### ISSUE THREAD

**Issue by davaymne** [graphprotocol/indexer#124]
`{"level":50,"time":1606398944498,"pid":1,"hostname":"5105fb8c4ead","name":"IndexerAgent","component":"Network","indexer":"0x14c7dB0Bf796060DA7212C0F851Ce62A47805502","operator":"0x14c7dB0Bf796060DA7212C0F851Ce62A47805502","err":{"type":"IndexerError","message":"Failed to query indexer allocations","stack":"IndexerError: Failed to query indexer allocations\n    at Object.indexerError (/opt/indexer/packages/indexer-common/dist/errors.js:91:12)\n    at Network.<anonymous> (/opt/indexer/packages/indexer-agent/dist/network.js:311:46)\n    at Generator.next (<anonymous>)\n    at fulfilled (/opt/indexer/packages/indexer-agent/dist/network.js:24:58)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)","code":"IE010","explanation":"https://github.com/graphprotocol/indexer/blob/master/docs/errors.md#ie010","cause":{"type":"b","message":"[Network] Bad Gateway","name":"CombinedError","graphQLErrors":[],"networkError":{"type":"Error","message":"Bad Gateway","stack":"Error: Bad Gateway\n    at /opt/indexer/node_modules/@urql/core/dist/e624b925.js:150:37\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)"},"response":{"size":0,"timeout":0}}},"msg":"Failed to query indexer allocations"}
{"level":40,"time":1606398944498,"pid":1,"hostname":"5105fb8c4ead","name":"IndexerAgent","err":{"type":"IndexerError","message":"Failed to synchronize with network","stack":"IndexerError: Failed to synchronize with network\n    at Object.indexerError (/opt/indexer/packages/indexer-common/dist/errors.js:91:12)\n    at Agent.<anonymous> (/opt/indexer/packages/indexer-agent/dist/agent.js:120:47)\n    at Generator.throw (<anonymous>)\n    at rejected (/opt/indexer/packages/indexer-agent/dist/agent.js:25:65)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)","code":"IE004","explanation":"https://github.com/graphprotocol/indexer/blob/master/docs/errors.md#ie004","cause":{"type":"IndexerError","message":"Failed to query indexer allocations","stack":"IndexerError: Failed to query indexer allocations\n    at Object.indexerError (/opt/indexer/packages/indexer-common/dist/errors.js:91:12)\n    at Network.<anonymous> (/opt/indexer/packages/indexer-agent/dist/network.js:311:46)\n    at Generator.next (<anonymous>)\n    at fulfilled (/opt/indexer/packages/indexer-agent/dist/network.js:24:58)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)","code":"IE010","explanation":"https://github.com/graphprotocol/indexer/blob/master/docs/errors.md#ie010","cause":{"type":"b","message":"[Network] Bad Gateway","name":"CombinedError","graphQLErrors":[],"networkError":{"type":"Error","message":"Bad Gateway","stack":"Error: Bad Gateway\n    at /opt/indexer/node_modules/@urql/core/dist/e624b925.js:150:37\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)"},"response":{"size":0,"timeout":0}}}},"msg":"Failed to synchronize with network"}`

**Comment by fordN** [comment]
This error message represents a transient error on the gateway side and is not something to be worried about generally.
