### ISSUE TITLE
Subgraphs moved to paused state once the network came back online

### ISSUE THREAD

**Issue by trader-payne** [graphprotocol/indexer#127]
The agent found no GRT in the wallet, thus he couldn't reallocate when the network came back online.
All subgraphs that were previously syncing, were moved to nodeid "removed", thus pausing everything.

**Comment by fordN** [comment]
@trader-payne have you seen this issue recently?

**Comment by trader-payne** [comment]
I haven't tried to reproduce it in a long time. But I can try
