### ISSUE TITLE
Subgraphs are (re)assigned randomly to index-nodes

### ISSUE THREAD

**Issue by trader-payne** [graphprotocol/indexer#128]
1. Have all of your subgraphs in a paused state (decisionBasis never)
2. Set all your allocations, and turn them on.
3. Notice them being reassigned randomly

Moreover, it doesn't "remember" which index-nodes it used in the past and if you stop/start everything again, it reassigns them randomly again.

**Comment by fordN** [comment]
It's probably worth turning this into a feature request:

Feature: support management of the node assignments in indexer-agent

**Comment by Aderks** [comment]
To add to this feature request, it would be great to assign which index-node to use when opening a new allocation.

`graph indexer rules set Qm... parallelAllocations 1 decisionBasis always allocationAmount 150000 indexNode <node_id>`

Have it optional and default with it's current logic, but if set in the rule command it'll assign the allocation to the given `node_id`.

We have multiple ETH sources (geth and Erigon). It would be great to be able to choose to send only `trace` subs to Erigon index-nodes and `non-trace` subs to geth index-nodes.

I've noticed the subgraph reassignments outlined by Payne and would love to have them be remembered.
