### ISSUE TITLE
No query fees collected on multiplication of variables

### ISSUE THREAD

**Issue by czarly** [graphprotocol/indexer#129]
I received no query fees for this cost model

```
default => $DAI * $Y;
```

but all was good when I changed it to this cost model

```
default => $DAI * 0.0019;
```

both times the following variables were set as reported by the indexer cli (cost get all) output:

```json
{
   "Y": "0.00019",
   "DAI": "10.0006390502074853"
}
```

**Comment by fordN** [comment]
@czarly Let me know if this is still a problem.  If not, I'll close this issue at the end of the week.
