### ISSUE TITLE
Too many requests done on rinkeby eth node - causing rate limit on free provider

### ISSUE THREAD

**Issue by sharppanda** [graphprotocol/indexer#130]
From yesterday, the new phase 2 start, I am facing rate limiting on infura rinkeby node (free tier). Based on a discussion on discord, I wasn't the only one.

The temporary suggested solution for now is to switch to alchemy free tier.

Here is the screenshot from SunTzu for about 12h of traffic
![Alchemy API](https://cdn.discordapp.com/attachments/755239678566858773/783256197112397844/Screen_Shot_2020-12-01_at_16.00.22.png)

**Comment by fordN** [comment]
With an initial solution to remedy this, I'll close this issue knowing there may be future optimizations possible.
