### ISSUE TITLE
Add a feature to allow for fast replacement of allocations

### ISSUE THREAD

**Issue by juanmardefago** [graphprotocol/indexer#134]
Currently it takes a long time for changes in our indexing rules to impact on chain (so far it seems to be around 6-12hs), and this makes it difficult to change allocation amounts and test different staking strategies in time.

@Jannis mentioned that they wanted to add a field to allow allocations to be modified faster, by telling the agent to trigger those modifications when the current epoch ends.

Would be a great addition, especially considering that we now can track query traffic changes much more quickly than we can react to them.

**Comment by fordN** [comment]
Related feature in progress: #200
