### ISSUE TITLE
Cannot set reverse ENS for tokenlock contract and therefore names on explorer will remain as addresses

### ISSUE THREAD

**Issue by danenright** [graphprotocol/indexer#155]
It seems that due to the requirement of using our vesting contracts as the indexer address these will remain as eth addresses on the network explorer as we cannot set a reverse ENS address on these.

![indexers-address](https://user-images.githubusercontent.com/2581435/102560042-63451800-4125-11eb-99a1-b154a3cbb604.jpg)

**Comment by linki** [comment]
@danenright The ENS names also work with the TokenLock contracts. Check the instructions [here](https://www.notion.so/Graph-Network-Token-Lock-Contract-Guide-Public-30992eea5f4b47c8b4c6ff7a9bc56a41) under "Setting a name for your account".
