### ISSUE TITLE
Indexing rewards are restaked despite restake-rewards=false

### ISSUE THREAD

**Issue by madumas** [graphprotocol/indexer#159]
With, INDEXER_AGENT_RESTAKE_REWARDS = false, indexing rewards are restaked upon closing a channel.

Example transaction: https://etherscan.io/tx/0x6516c48fa3f31be17cb22c3cccafee885cfa17fd34a77935ce388cfc8771cfc1

**Comment by fordN** [comment]
@madumas I just did some testing and found that the `..NO_RESTAKE_REWARDS` env variable does not work as expected.   Here are the options I'm aware of for setting `restakeRewards` to `false`:
  - `--restake-rewards=false`
  - `--no-restake-rewards=true`
  - `INDEXER_AGENT_RESTAKE_REWARDS=false`

**Comment by kyle-u410** [comment]
It appears the `restakeRewards` IndexerOption is not used anywhere in the code. Could we please remove this command line argument?
