### ISSUE TITLE
Report mainnet errors  about the IE007, IE009 ,IE011  , when  indexer in china, improve the network of network-subgraph-endpoint

### ISSUE THREAD

**Issue by sun1534** [graphprotocol/indexer#171]
the endpoint   of  my used:
--network-subgraph-endpoint https://gateway.network.thegraph.com/network

i  know the reasons for, is  "The endpoint is unhealthy or unreliable."
i have a  Bare-Metal  in IDC. of china. my  indexer services of mainnet  on  it

can we improve the network of network-subgraph-endpoint ?
maybe , a list of  network-subgraph-endpoint address?
so anyone indexer  could  choose the  best one for self

erros:
`"code":"IE011","explanation":"https://github.com/graphprotocol/indexer/blob/master/docs/errors.md#ie011","cause":{"type":"b","message":"[Network] request to https://gateway.network.thegraph.com/network failed, reason: connect ETIMEDOUT 104.18.10.19:443"`

`"code":"IE007","explanation":"https://github.com/graphprotocol/indexer/blob/master/docs/errors.md#ie007","cause":{"type":"b","message":"[Network] request to https://gateway.network.thegraph.com/network failed, reason: connect ETIMEDOUT 104.18.10.19:443"`

`"code":"IE009","explanation":"https://github.com/graphprotocol/indexer/blob/master/docs/errors.md#ie009","cause":{"type":"b","message":"[Network] request to https://gateway.network.thegraph.com/network failed, reason: connect ETIMEDOUT 104.18.10.19:443"`

**Comment by fordN** [comment]
It's now possible to supply the agent with the deployment id of the network subgraph and it will sync it locally for you and use it when ready.  Use the `--network-subgraph-deployment` parameter to use this feature.
