### ISSUE TITLE
AllocateFrom failing using an already used allocationID

### ISSUE THREAD

**Issue by abarmat** [graphprotocol/indexer#174]
An `allocateFrom()` call failed with error `!null` meaning that it tried to reuse an allocationID.

This happened because there were two allocateFrom() transactions in the mempool. The first one was sent with 27gwei gas price, it was probably sitting there and then a second one with same data was sent some time later with a higher gas 57gwei.

Probably the second one unstuck the one with lower nonce as these were mined on the same block. It is good that this happened but let check if it was an expected behaviour and how the agent decided to send the second transaction.

### Details

> AllocationID `0xdccd5bfe7c23a433fa72a169b9355730457cca2d`
1) nonce:9  gwei: 27 allocateFrom() -> SUCCESS https://etherscan.io/tx/0xc58f945a130041781fef9a3700f9068f796cf7d45d87147ea38143ada058c8cd
2) nonce:10 gwei: 52 allocateFrom() -> REVERTED
https://etherscan.io/tx/0xd3d8c1226ce05d622d277fe170f22844b8bac6b183e57986ba6bc0e08ec37745 << repeated allocation ID

Mined on the same block `11503389`

**Comment by fordN** [comment]
Transaction management has been significantly updated since this report with #212
