### ISSUE TITLE
cannot search by ENS name on network site

### ISSUE THREAD

**Issue by danenright** [graphprotocol/indexer#177]
Can we add the ability to search by ENS name rather than wallet address?

<img width="442" alt="Screen Shot 2020-12-24 at 12 25 17 pm" src="https://user-images.githubusercontent.com/2581435/103048665-6f2c5080-45e3-11eb-8f5a-305d94ea9fa8.png">

**Comment by fordN** [comment]
Moved to the graphprotocol/network-support repo
