### ISSUE TITLE
Feature: Gas Control Variables

### ISSUE THREAD

**Issue by fattox** [graphprotocol/indexer#178]
I was showing Jannis the way Chainlink handle gas pricing with their nodes, and he liked the ideas, especially:

- Resubmitting when a tx isn't mined
- Configuring how the gas amount is bumped

Feel free to take a look for some ideas on how we can handle it on our own agent to avoid the issues we've seen lately.
https://docs.chain.link/docs/configuration-variables#eth_gas_bump_threshold

**Comment by fordN** [comment]
Resolved with #212
