### ISSUE TITLE
Incorrect BalanceOf Data

### ISSUE THREAD

**Issue by crypto-yang** [graphprotocol/indexer#181]
Hello,

There seems to be something wrong the balanceOf for one specific event. All other events seem to work fine except for this one. Now matter how many ways I've tried to get a value using subgraph, it always returns zero. 

I checked the balanceOf using other platforms such as https://etherscan.io/tokencheck-tool and it returns a correct value.

I believe there is something not quite right with the indexer

I've made a subset of my code to isolate the issue, please help me take a look

Here is my subgraph code
https://github.com/crypto-yang/graph-usdt-usdc-pool

Here is the hosted subgraph
https://thegraph.com/explorer/subgraph/crypto-yang/swapdataclone?selected=playground

Here is the query producing a zero result

```
{
  transferEntities (where: { blockNumber: 10861439 }) {
    id
    from
    to
    amount
    blockNumber
    rawAmount
    rawBalanceOf
  }
}

```

**Comment by fordN** [comment]
@crypto-yang have you been able to resolve this issue?  
If not, can we move it over to the graph-node repo which would be the place to report syncing issues?
