### ISSUE TITLE
Feature request: 🗿 Permanent subgraphs 

### ISSUE THREAD

**Issue by pi0neerpat** [graphprotocol/indexer#192]
## Problem

I am a Dapp Developer in addition to an indexer. 

I'd like to be able to add them to my indexer stack, regardless of whether they are "in-network". 

The indexer-agent should **never** remove them.

I do not want to have to run an additional `gaph-node` to do this.

## Potential Solution 

From Jannis: A subgraph name prefix that the agent is responsible for and everything else it leaves alone

Back in the old days we could use `subgraph_deploy` and other CLI commands which are now unavailable. It'd be nice to get that functionality back

Thanks!

**Comment by fordN** [comment]
Support added with #213!
