### ISSUE TITLE
Feature request - Gateway IP addresses as a flat text file in the indexer repo

### ISSUE THREAD

**Issue by cryptovestor21** [graphprotocol/indexer#203]
During testnet the gateway ip addresses were updated via a file (in the mission control repo, I think?).

Would it be possible to do this again for mainnet? An indexer has requested the ability to query the list of ip addresses and a continually updated file in the indexer repo might be the right solution.

Source: https://forum.thegraph.com/t/another-way-to-get-gateway-source-ip-addresses/233

**Comment by fordN** [comment]
Unfortunately the gateway IPs cannot be expected to be stable on Mainnet at the moment, so a consistent whitelist isn't available.
