### ISSUE TITLE
FR: Close and Allocate in one transaction

### ISSUE THREAD

**Issue by davaymne** [graphprotocol/indexer#205]
Problem statement
Currently, 2 x eth transactions required to “renew” existing allocation.
Indexer has to close existing allocation and open new allocation (potentially with new parameters, e.g. allocationAmount) then. Having high gas cost, such 2 x operations could financialy impact indexer.

Proposed solution
Consider to update Indexer-Agent with new operation closeAndAllocate(), wich would allow to close and open allocation in one transaction, which could potentially reduce Indexer’s operational costs.

Operation closeAndAllocate() would intake optional argument:
* newAllocationAmount
Use:
graph indexer rules set "deployment" newAllocationAmount 1000
It would close existing allocation and reopen with new amount 1000

Discussion on [forum](https://forum.thegraph.com/t/close-and-allocate-in-one-transaction/758).

**Comment by fordN** [comment]
Being worked on in #258
