### ISSUE TITLE
indexer-agent always exits with fatal error: CALL_EXCEPTION for method: paused()

### ISSUE THREAD

**Issue by begetan** [graphprotocol/indexer#207]
Versions:
- indexer-agent: 0.10.0
- indexer-service: 0.10.0
- graph-node: 0.21.1

Environment:
- New testnet configuration
- Database is running
- Graph-node is running and scanning blocks from the Ethereum node.
 
Expected behavior: 
After launch container should check all settings and provide notifications like "waiting for the node operator wallet approval from staking contract"  It could be checked in the loop every 1-5 minutes.

Actual behavior:
Service exits with a fatal error. It makes it very hard to verify the configuration.

Logs:
https://gist.github.com/begetan/74d28161bb9ce7eb8fdc15eb1811fc8c

**Comment by begetan** [comment]
I found that I set the indexer address the same as the operator address initially ( before the token distribution) 
While it is a correct configuration I am trying to set up a separate node management wallet.

So I did the following steps. 

1) Assign a node wallet with 1 Eth balance, and use the same address for indexer - > got  code: `'CALL_EXCEPTION' for method: 'paused()'`

2)  Approved node operator address using cli.ts using testnet instructions -> still got the same error

3) Proceeded entire initialization flow:  
1. Approve token distribution for 1M testnet tokens
2. Stake amount 100K
3. Approved node operator address one more time
4. Set correct Indexer address and operator wallet

All transactions succeded for an account: https://rinkeby.etherscan.io/address/0x3ad34B9dFaEefaeD3CdB2C60Ea93EAe60463DedF

And the result is absolutely the same. I think there is a general issue in the interaction between index-agent and testnet contract dispatching address: `0x23B1aD50996ff1b21552cDD6430868D60bF342c5`

**Comment by begetan** [comment]
The root cause of this error was the incorrect Ethereum node endpoint in the indexer agent and the indexer service configurations. It was set for Mainnet instead of Rinkeby.

Anyway, it could be nice to implement better error handling for such a case. So I would like to keep it open untill the dev team makes a decision.

**Comment by begetan** [comment]
I have the same error message when running on Mainnet.

https://gist.github.com/begetan/6e4b2fb5021ee6b5b4917284ba9e40ec

This time I doubled checked everything. The issue was with indexer-agent which doesn't work with OpenEthereum endpoint, while indexer-service does. 

It would be great to add here all kind of  network checking and provides a correct error message instead of a fatal exception

**Comment by hopeyen** [comment]
Issue created for adding more types of indexer configurations check such as ethereum endpoints: https://github.com/graphprotocol/indexer/issues/448
