### ISSUE TITLE
Feature request: CLI commands to allocate to a specific subgraph version

### ISSUE THREAD

**Issue by trader-payne** [graphprotocol/indexer#215]
Right now, there is no way to deploy a specific version of a subgraph, and if the subgraph that you allocated has a new version deployed, usually most of the signal is auto-migrated to it, leaving all indexers without rewards.

My suggestion is to have a bunch of CLI commands to differentiate between the way you allocate:
- allocate against a deployment
- allocate against a specific subgraph version
- toggle to auto-migrate allocation to the version of the deployment that has the most signal (maybe as an indexer agent variable?)
- toggle to auto-migrate allocation to the new version regardless of signal value (maybe as an indexer agent variable?)

**Comment by fordN** [comment]
Allocating against a deployment _is_ equivalent to allocating towards a specific version. ;) 

I do think an additional rule identifier that allows indexers to specify a subgraph name and an auto-migrate pattern could be an incredibly useful addition though!

**Comment by trader-payne** [comment]
Yeah, indeed. I clarified this later on but I never had the chance to correct myself.

And yes, the auto-migrate would be a fantastic feature to have 🥳
