### ISSUE TITLE
Execute transaction can return empty receipt

### ISSUE THREAD

**Issue by abarmat** [graphprotocol/indexer#227]
The executeTransaction function can return an empty receipt after all the retries but it is not checked in code below that call. 

**executeTransaction call:**
https://github.com/graphprotocol/indexer/blob/66705cf0aff183307d249293f441fbe03d473dfb/packages/indexer-agent/src/network.ts#L914

**Uses empty receipt**
https://github.com/graphprotocol/indexer/blob/66705cf0aff183307d249293f441fbe03d473dfb/packages/indexer-agent/src/network.ts#L949

**Comment by fordN** [comment]
@abarmat this issue is kind of old, do you think it's something we should look into?

**Comment by abarmat** [comment]
We don't, the agent changed quite a bit since my report. You can close an reopen if we see something odd/related. @fordN
