### ISSUE TITLE
Feature Request - Don't stop syncing the subgraph until allo is closed

### ISSUE THREAD

**Issue by trader-payne** [graphprotocol/indexer#235]
**Scenario:**
- you allocated to a subgraph
- you want to close the allo next epoch (as soon as you can)
- you set it to `decisionBasis never`

**Behavior:**
- agent removes the deployment and stops syncing the subgraph

**Problem:**
- you need a POI based on the new epoch block, but you won't have it since the subgraph is stopped from indexing immediately after the `decisionBasis never` command

**Result:**
- the allocation won't be closed because the POI cannot be generated

**Comment by fordN** [comment]
Being addressed in #237
