### ISSUE TITLE
Feature: Support seamless network-subgraph version updates via indexer-cli

### ISSUE THREAD

**Issue by fordN** [graphprotocol/indexer#247]
Currently the network subgraph deployment and endpoint can be controlled via startup parameters.  With a recent update an indexer is able to update the version of their network endpoint without downtime using a combination of the offchain-subgraph, network-endpoint, and network-subgraph-deployment features.  It would be amazing to be able to control this process with a simple indexer-cli command. 

For a strawman proposal, the command could look something like: `indexer network update Qm...`

**Comment by hopeyen** [comment]
@fordN do you think we should close this? I think here's what we agreed on:

Indexer-agent instantiates the networkSubgraph on startup and uses that everywhere. Refreshing fields based on the network seems like a big lift not necessarily worth the improvement in usability right now.

We explored the option of building a default network subgraph deployment into the agent and release new versions with new subgraph versions, which we can discuss after reaching to a more regular release schedule.

**Comment by fordN** [comment]
@hopeyen agreed! I'll keep the issue open to track it, but move it back on the `[Indexer Experience project board](https://github.com/orgs/graphprotocol/projects/20/views/2)`.
