### ISSUE TITLE
Bug: Potential trigger for other allocations than for the desired one

### ISSUE THREAD

**Issue by Chainode** [graphprotocol/indexer#249]
Release: v0.15.1

Prior to upgrading to v0.15.1 all allocations have been closed. 

After upgrading to the latest release and starting again the graph-node, indexer agent and indexer service, the following command was used to make a single allocation:
graph indexer rules set QmRhYzT8HEZ9LziQhP6JfNfd4co9A7muUYQhPMJsMUojSF decisionBasis always allocationAmount 4100000 parallelAllocations 1

This has though triggered multiple "Allocate From" transactions, that have failed but costed ETH gas fees. 

![image](https://user-images.githubusercontent.com/53407923/119732902-17875f00-be79-11eb-89c3-d623dde37256.png)

Prior to this upgrade this behavior has never happened. 
The indexer agent has been started with the flag --network-subgraph-deployment QmaUBw7sr8pBrwNgz6JkbmmGoUU7KJSaeRvCaY3NPDbQ7A in case it has any relevance. 

We create another allocation a bit later and that didn't triggered any further Allocate From" transactions. Maybe the issue is gone but would still be interesting to find what has caused this if possible as it has costed some eth fees and can potentially cost more if this reoccurs during a very high gas fees period. 

Expected behavior: no further "Allocate From" transaction should be triggered if it hasn't be made on purpose by an indexer. 

If we observe further events relevant to this issue, we will update it with new information.

**Comment by fordN** [comment]
This issue appears specific to an older version of the software and has since been resolved, closing.
