### ISSUE TITLE
Feature request: Reconcile allocations and cost models

### ISSUE THREAD

**Issue by chriswessels** [graphprotocol/indexer#271]
Currently there's no built-in process to ensure that any subgraphs that are allocated to also have a cost model defined.

This makes it unfortunately easy for indexers to do the work of indexing a subgraph, without having the prerequisites in place to actually serve queries for it.

Some ideas:
- Update the existing reconciliation loop to check if cost models are defined for all subgraphs, and log a warning if this is not the case
- Allow a default cost model to be defined which will be served for any subgraph that doesn't have a specific cost model defined

**Comment by fordN** [comment]
Being worked on in #381.
