### ISSUE TITLE
indexer-agent: Allow API-driven modification of offchain subgraphs list

### ISSUE THREAD

**Issue by chriswessels** [graphprotocol/indexer#281]
Indexers are using the `--offchain-subgraphs` flag in indexer-agent to presync a subgraph before allocating it, to ensure that subgraph is synced (and therefore a valid POI can be produced) before allocating on-chain. This is because some subgraphs can take in excess of 28 days to sync, so if allocating immediately, you risk losing indexing rewards if a delegator closes the expired allocation with a 0x0 POI.

Currently this process of managing the presyncing list is cumbersome, because the list must be passed to indexer-agent as a startup argument. It would be great if the list of offchain subgraphs could be modified using indexer-agent's API. This would also unlock management of this list using indexer-cli.

**Comment by hopeyen** [comment]
Hi Chris! Issue should be solved [here](https://github.com/graphprotocol/indexer/pull/350)
With the new variant `offchain` in `IndexingRules.DecisionBasis`, you can manage offchain syncing subgraphs using indexer-cli. 
Note that the implementation for the list `--offchain-subgraphs` has not been changed, I think the improvement for it can wait until we review this [issue](https://github.com/graphprotocol/indexer/issues/296) :)
