### ISSUE TITLE
indexer-agent: Indexer rules update triggers immediate deployment allocation reconciliation

### ISSUE THREAD

**Issue by fordN** [graphprotocol/indexer#282]
Currently indexing rule updates do not immediately trigger reconciliation and the delayed response causes distrust of the agent and encourages taking actions outside the agent.  Rule change events should lead to immediate reconciliation and, if applicable, on-chain action.

**Comment by Aderks** [comment]
@fordN any idea on how this will be addressed? 

IMO, the largest issue with this delayed response is with on-chain events (closing / opening allo's). If there is a lot of required work to make the rule change events immediate, could an interim solution be to have the agent `default: 120_000` ms loop time configurable as seen in this update to the service nodes (https://github.com/graphprotocol/indexer/pull/229/commits/568df2610f25e4b56c837e05defd696b9d780f58) ?

Would there be any negative effects to making the reconciliation loop quicker as opposed to the 2 minutes?

**Comment by fordN** [comment]
@Aderks this issue has been resolved with the merging of #352 and will be included in the next release.
