### ISSUE TITLE
too many txs in queue

### ISSUE THREAD

**Issue by mindstyle85** [graphprotocol/indexer#290]
"type": "Error",
        "message": "There are too many transactions in the queue. Your transaction was dropped due to limit. Try increasing the fee.",
        "stack":
        
Getting the above error again, with no pending onchain allocation, so it seems this is solely in the local software...

Version is the one before v17..

**Comment by fordN** [comment]
Interesting. Do you have indexer-agent logs or Etherscan link to show what transactions it was sending, how many it was trying to send, and why?

**Comment by mindstyle85** [comment]
I can find them but i can describe what i did:

1. i have closed an allocaton which went well
2. i opened an allocation on another subgraph
3. changed my mind and changed allocation to 0
4. allocated to another subgraph

I can try to dig out the logs when i get some more time (theyre buried deep already), but this was mostly it.

Upgrading to v17 solved it later on, that was basically my solution to this problem.

**Comment by fordN** [comment]
Closing as the issue appears specific to an older version of the software.
