### ISSUE TITLE
Feature Request: add a flag to point to a file that lists all offchain subgraphs to sync as an alternative to passing an array of subgraphs

### ISSUE THREAD

**Issue by Pete-LunaNova** [graphprotocol/indexer#296]
The new `--offchain-subgraphs` flag for the indexer-agent is very handy, thank you for implementing this. 

It would be great to augment it with another option: to be able to pass a path to a file that contains a list of subgraphs to sync "offchain" instead of being limited to passing an array as an argument when executing the binary. The file could contain one deplyoment id per line. Having this option would better suit some automation workflows.

**Comment by cryptovestor21** [comment]
I'd also like to be able to add a name field to that file, just so i can keep tabs on the names versus the ipfs hashes.

**Comment by czarly** [comment]
INDEXER_AGENT_OFFCHAIN_SUBGRAPHS=$(grep . /path/to/offchain-subgraphs.txt | xargs | sed -e 's/ /,/g')

**Comment by fordN** [comment]
Closing as czarly provided a good workaround and hopeyen implemented offchain subgraph management in the indexer-cli (or via GraphQL requests directly to the indexer management server of the indexer-agent) in PR #281 .
