### ISSUE TITLE
indexer-agent: IE054: Failed to collect receipts in exchange for query fee voucher, Request body larger than maxBodyLength limit

### ISSUE THREAD

**Issue by begetan** [graphprotocol/indexer#331]
There is a lot of error messages in indexer-agent log regarding large request body:

Running in Docker.

graph-node version 0.24.2
indexer-agent version: 0.17.0

Full error log is [here](https://gist.github.com/begetan/311f881bce7857f9e26f762014807d4c)

**Comment by fordN** [comment]
I've created an issue to track the work to resolve this issue, #383.
