### ISSUE TITLE
Add indexing rule field for subgraphs that are not fully supported

### ISSUE THREAD

**Issue by Jannis** [graphprotocol/indexer#356]
This would allow indexers (e.g. in the global rule) to reject any subgraphs that are not fully supported and for which they cannot receive indexing rewards. Without this field, they might pick up such subgraphs without noticing and basically burn ETH for nothing.

**Comment by hopeyen** [comment]
Hello Jannis! Issue resolved [here](https://github.com/graphprotocol/indexer/pull/362)
Agent should now automatically reject allocating to unsupported subgraphs, and one can bypass specific deployments using boolean field `requireSupported` in indexing rules
