### ISSUE TITLE
Agent doesn't refresh POI when waiting for lower gas

### ISSUE THREAD

**Issue by sharppanda** [graphprotocol/indexer#413]
The agent seems to close (closeAndAllocate and possible with close as well) an allocation with poi from previous epoch.
When the epoch changes and allocation have 27 days, the agent tries to close the allocation. It retrieves the POI (not sure why, but at that moment it gets the allocation from past epoch). This poi is then used for the transaction.
If the gas limit is not under the limit, the operation retries. When successful it seems that it uses the previous POI (doesn't generate new one).
Also during the retry period it seems that the agent doesn't react on any new changes in indexing rules.

**Comment by sharppanda** [comment]
Hi,

I see the issue when the gas limit is reached. It retries until the gas is below the given limit. After that I assume it submits with the POI from first try.

During these retries the agents accept change rules requests, but for example if I add a rule `decisionBasis: always` the graph node doesn't start to index before the retries are gone. If I restart the agent it works.

**Comment by fordN** [comment]
Great observation @sharppanda!  I'm working on a big update (Action queue) right now that will include a fix to this behavior you observed.  In the new paradigm the POI will be resolved only when the close allocation transaction is about to be sent (and will re resolve it on a retry.)

**Comment by sharppanda** [comment]
Great to hear @fordN 👏 
Do you want to close the issue or leave it open and link it to new version fixing this behavior?

**Comment by fordN** [comment]
@sharppanda I typically close the relevant issue when merging the PR.  Here's the [draft PR](https://github.com/graphprotocol/indexer/pull/419) in progress.

**Comment by fordN** [comment]
Closing this as it was resolved in #419
