### ISSUE TITLE
Why this error

### ISSUE THREAD

**Issue by ordifind** [graphprotocol/indexer#433]
Subgraph failed with non-deterministic error: failed to process trigger: block #19194303 (0x6f6c…443c), transaction cf85d788f16e4827fa9c7248bce8a89e7f9882c307d55da11904dd6e6fe7d06e: `allocate` function not found, retry_delay_s: 240, attempt: 1

**Comment by fordN** [comment]
Hey @sameerneupane this appears to be an issue with the subgraph itself.

Could you share the subgraph deployment ID?

**Comment by samirneupane62** [comment]
the issue is solved ,, But why the subgrah is syncing very slowly

**Comment by fordN** [comment]
@samirneupane62 I'd suggest popping into [the discord](https://github.com/graphprotocol) #subgraph-development channel to discuss ways to speed up your subgraph.  

Or if you would like to provide details here I can point you to documentation or provide suggestions, but the feedback loop will be slower here.

**Comment by fordN** [comment]
Closing this issue as it's old.
