### ISSUE TITLE
Cannot read property 'latitude'

### ISSUE THREAD

**Issue by wetezos** [graphprotocol/indexer#440]
When i execute the orders `graph indexer status` , i got follow error.

cli version:0.19.1
npm i -g @graphprotocol/indexer-cli@0.19.1 --registry 

GEO_COORDINATES="51.2993 9.491"

 

`graph indexer status
/home/graph/.npm-global/lib/node_modules/@graphprotocol/indexer-cli/node_modules/gluegun/build/index.js:13
    throw up;
    ^

TypeError: Cannot read property 'latitude' of null
    at /home/graph/.npm-global/lib/node_modules/@graphprotocol/indexer-cli/dist/commands/indexer/status.js:157:72
    at Generator.next (<anonymous>)
    at fulfilled (/home/graph/.npm-global/lib/node_modules/@graphprotocol/indexer-cli/dist/commands/indexer/status.js:6:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)`

**Comment by hopeyen** [comment]
hey 👋  I ran my setup with your coordinates on v0.19.1 and I didn't encounter the error above. I think I might've made a suggestion to you on discord about registering the indexer, but not sure if it helped. 

If you are still having the issue, would you mind sharing the log when you startup indexer-agent? hopefully you can see something like 
```
[1659138569467] INFO (IndexerAgent/40253 on book): Register indexer
    component: "Network"
    indexer: "0xE9a1CABd57700B17945Fd81feeFba82340D9568F"
    operator: "0xE9a1CABd57700B17945Fd81feeFba82340D9568F"
    address: "0xE9a1CABd57700B17945Fd81feeFba82340D9568F"
    url: "http://localhost:7600/"
    geoCoordinates: [
      "51.2993",
      "9.491"
    ]
    geoHash: "u1nezfz0h"
```
If it is the first time registering then you should see info logs on transactions sending, pending, successfully included in block, and finally successfully registered.
