### ISSUE TITLE
Global rule with `always` overrides deployment rule with `rules` or `never`

### ISSUE THREAD

**Issue by Jannis** [graphprotocol/indexer#45]
This was reported by a user. Their agent tried to index the deployment `QmZoyXk57CrzANVKnv4AQES1X3UrzXb2weNGqfTLHAdfri`, even though the rules expressed never to index it. 

![image](https://user-images.githubusercontent.com/19324/91980234-37915400-ed27-11ea-9b6f-eb6b59a01d03.png)

My theory is that the global rule somehow took priority.

**Comment by fordN** [comment]
This hasn't been reported since, please open another issue if the problem arises again.
