### ISSUE TITLE
Action Queue improvements (AQI)

### ISSUE THREAD

**Issue by fordN** [graphprotocol/indexer#451]
Creating this issue to track UX friction experienced when using the action queue and to propose improvements.

- [x] https://github.com/graphprotocol/indexer/issues/445
- [x] https://github.com/graphprotocol/indexer/issues/444
- [x] https://github.com/graphprotocol/indexer/issues/449
- [x] #442 
- [x] https://github.com/graphprotocol/indexer/issues/450
- [x] https://github.com/graphprotocol/indexer/issues/502

**Comment by fordN** [comment]
- [ ] #442

**Comment by cryptovestor21** [comment]
I have lots of cancelled actions in the output of graph indexer get actions and would like an option to purge cancelled actions, or hide them from the output, or whatever folks think makes sense to make graph indexer get actions more usable over time. It seems that something similar might be useful for failed actions too, although so far I have just been cancelling failed actions.

**Comment by fordN** [comment]
The set of projects to achieve this epic have all been completed.  Closing
