### ISSUE TITLE
Add prometheus metric for value of uncollected and unredeemed fees for each allocation

### ISSUE THREAD

**Issue by chriswessels** [graphprotocol/indexer#464]
It would be great to have indexer-agent export some metrics relating to query fees, including those that are actively being received as receipts and have not yet been collected (swapped for a voucher), as well as vouchers that have not yet been redeemed on-chain.

**Comment by fordN** [comment]
@hopeyen was this resolved in #597 ?

**Comment by hopeyen** [comment]
> @hopeyen was this resolved in #597 ?

yes!

**Comment by hopeyen** [comment]
(Feel free to re-open for adjusting or requesting more related metrics
