### ISSUE TITLE
TypeError: print.highlight  is not a function in v20.1 client output

### ISSUE THREAD

**Issue by cryptovestor21** [graphprotocol/indexer#468]
When listing all rules with `graph indexer rules get all` the output is correct however there is an error message at the end of the output:

`TypeError: print.highlight is not a function`

indexer-agent v20.2 (built from docker image)
indexer-cli 20.1(built from stakesquid cli build scripts here https://github.com/StakeSquid/graphprotocol-mainnet-docker/tree/master/cli)

<img width="411" alt="image" src="https://user-images.githubusercontent.com/59484786/186169556-c6c24058-eae1-4467-9501-d38d5bee8de8.png">

**Comment by hopeyen** [comment]
Hello 👋 ! 
I wasn't able to reproduce the issue, and our CLI kit 'gluegun''s toolbox should include different prints like `highlight`, `success`, and `warn`. I wonder if there's an issue with the dependencies there, but I think we can just print it normally for now, so I will change `highlight` prints to normal prints

**Comment by erockstroh** [comment]
Hello!

I am encountering the same issue, although with a different call.

```
graph@13d41b5e795b:~$ node -v
v14.20.0
graph@13d41b5e795b:~$ graph version
0.33.0
graph@13d41b5e795b:~$ graph indexer status
/home/graph/.npm-global/lib/node_modules/@graphprotocol/indexer-cli/node_modules/gluegun/build/index.js:13
    throw up;
    ^

TypeError: print.highlight is not a function
    at /home/graph/.npm-global/lib/node_modules/@graphprotocol/indexer-cli/dist/commands/indexer/status.js:210:19
    at Generator.next (<anonymous>)
    at fulfilled (/home/graph/.npm-global/lib/node_modules/@graphprotocol/indexer-cli/dist/commands/indexer/status.js:6:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

The code is running in a custom container that has installed the above Node version (14.20.0), the graph-cli version 0.33.0, and the indexer-cli version 0.20.3.

**Comment by hopeyen** [comment]
hey @erockstroh thanks for the report. I'm still unable to reproduce the issue, do you mind trying either of these two commands? 
```
graph indexer status --output=json
graph indexer status --output=yaml
```

**Comment by erockstroh** [comment]
Both of these work without any issues.

It almost seems like for whatever reason the `gluegun` package is being used (which is why it's throwing the issue with its own function), but then "print" is imported from somewhere else.

Would the Dockerfile that we are using help?

**Comment by sorcer1122** [comment]
I am facing exactly the same issue, is there a solution?
