### ISSUE TITLE
IndexerError:error starting indexer

### ISSUE THREAD

**Issue by jian-guo-s** [graphprotocol/indexer#475]
When I start the indexer through the docker container (goerli network), the following errors appear in the graph node and graph agent. However, before the goerli network is migrated, the rinkeby network is OK.
1.graph-node:

> ERRO subgraph_deploy failed, params: SubgraphDeployParams { name: SubgraphName("indexer-agent/HDukfRvzD4"), ipfs_hash: DeploymentHash("QmNhsC5jwSvwgYFdjBrjcc2YW8o7Xmo2WNZUHDukfRvzD4"), node_id: Some(NodeId("default")), debug_fork: None }, error: NetworkNotSupported(no network goerli found on chain ethereum), component: JsonRpcServer

2.graph-agent:

> {
	"level": 50,
	"time": 1662026466970,
	"pid": 1,
	"hostname": "8033f79b9fda",
	"name": "IndexerAgent",
	"name": "indexer-agent/HDukfRvzD4",
	"deployment": {
		"bytes32": "0x056f4f91f7964832568bd313c0c1290de220da9ea05c50b8d8d5ea5138e52007",
		"ipfsHash": "QmNhsC5jwSvwgYFdjBrjcc2YW8o7Xmo2WNZUHDukfRvzD4"
	},
	"err": {
		"type": "IndexerError",
		"message": "Failed to deploy subgraph deployment",
		"stack": "IndexerError: Failed to deploy subgraph deployment\n    at indexerError (/opt/indexer/packages/indexer-common/dist/errors.js:143:12)\n    at Indexer.<anonymous> (/opt/indexer/packages/indexer-agent/dist/indexer.js:522:63)\n    at Generator.next (<anonymous>)\n    at fulfilled (/opt/indexer/packages/indexer-agent/dist/indexer.js:5:58)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
		"code": "IE026",
		"explanation": "https://github.com/graphprotocol/indexer/blob/master/docs/errors.md#ie026",
		"cause": {
			"code": 0,
			"message": "network not supported by registrar: no network goerli found on chain ethereum"
		}
	},
	"msg": "Failed to deploy subgraph deployment"
}
{
	"level": 40,
	"time": 1662026929293,
	"pid": 1,
	"hostname": "8033f79b9fda",
	"name": "IndexerAgent",
	"component": "Network",
	"indexer": "0xeaF8F03f43499C2a906aefF411DEc3F8cf0DC584",
	"operator": "0xf62f714568ee067e44aD41d8652aEA9F3d8B2F3a",
	"err": {
		"type": "IndexerError",
		"message": "Failed to check for network pause",
		"stack": "IndexerError: Failed to check for network pause\n    at indexerError (/opt/indexer/packages/indexer-common/dist/errors.js:143:12)\n    at /opt/indexer/packages/indexer-common/dist/network.js:582:60\n    at Generator.throw (<anonymous>)\n    at rejected (/opt/indexer/packages/indexer-common/dist/network.js:6:65)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
		"code": "IE007",
		"explanation": "https://github.com/graphprotocol/indexer/blob/master/docs/errors.md#ie007",
		"cause": {
			"message": "connect ETIMEDOUT 104.18.39.222:443",
			"stack": "Error: connect ETIMEDOUT 104.18.39.222:443\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)",
			"config": {
				"transitional": {
					"silentJSONParsing": true,
					"forcedJSONParsing": true,
					"clarifyTimeoutError": false
				},
				"transformRequest": [null],
				"timeout": 0,
				"xsrfCookieName": "XSRF-TOKEN",
				"xsrfHeaderName": "X-XSRF-TOKEN",
				"maxContentLength": -1,
				"maxBodyLength": -1,
				"headers": {
					"Accept": "application/json, text/plain, */*",
					"Content-Type": "application/json",
					"User-Agent": "axios/0.26.1",
					"Content-Length": 54
				},
				"baseURL": "https://gateway.testnet.thegraph.com/network",
				"responseType": "text",
				"method": "post",
				"url": "",
				"data": "{\"query\":\"{\\n  graphNetworks {\\n    isPaused\\n  }\\n}\"}"
			},
			"code": "ETIMEDOUT",
			"status": null
		}
	},
	"paused": false,
	"msg": "Failed to check for network pause, assuming it has not changed"
}
{
	"level": 40,
	"time": 1662027041326,
	"pid": 1,
	"hostname": "8033f79b9fda",
	"name": "IndexerAgent",
	"component": "Network",
	"indexer": "0xeaF8F03f43499C2a906aefF411DEc3F8cf0DC584",
	"operator": "0xf62f714568ee067e44aD41d8652aEA9F3d8B2F3a",
	"err": {
		"type": "IndexerError",
		"message": "Failed to check operator status for indexer",
		"stack": "IndexerError: Failed to check operator status for indexer\n    at indexerError (/opt/indexer/packages/indexer-common/dist/errors.js:143:12)\n    at /opt/indexer/packages/indexer-common/dist/network.js:608:146\n    at Generator.throw (<anonymous>)\n    at rejected (/opt/indexer/packages/indexer-common/dist/network.js:6:65)",
		"code": "IE008",
		"explanation": "https://github.com/graphprotocol/indexer/blob/master/docs/errors.md#ie008",
		"cause": {
			"type": "Error",
			"message": "missing revert data in call exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (error={\"reason\":\"timeout\",\"code\":\"TIMEOUT\",\"requestBody\":\"{\\\"method\\\":\\\"eth_call\\\",\\\"params\\\":[{\\\"from\\\":\\\"0xf62f714568ee067e44ad41d8652aea9f3d8b2f3a\\\",\\\"to\\\":\\\"0x35e3cb6b317690d662160d5d02a5b364578f62c9\\\",\\\"data\\\":\\\"0xb6363cf2000000000000000000000000f62f714568ee067e44ad41d8652aea9f3d8b2f3a000000000000000000000000eaf8f03f43499c2a906aeff411dec3f8cf0dc584\\\"},\\\"latest\\\"],\\\"id\\\":343,\\\"jsonrpc\\\":\\\"2.0\\\"}\",\"requestMethod\":\"POST\",\"timeout\":120000,\"url\":\"https://eth-goerli.g.alchemy.com/v2/LQg0epkAO4qxklbMgbFuiG6azP6DsBAb\"}, data=\"0x\", code=CALL_EXCEPTION, version=providers/5.6.2)",
			"stack": "Error: missing revert data in call exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (error={\"reason\":\"timeout\",\"code\":\"TIMEOUT\",\"requestBody\":\"{\\\"method\\\":\\\"eth_call\\\",\\\"params\\\":[{\\\"from\\\":\\\"0xf62f714568ee067e44ad41d8652aea9f3d8b2f3a\\\",\\\"to\\\":\\\"0x35e3cb6b317690d662160d5d02a5b364578f62c9\\\",\\\"data\\\":\\\"0xb6363cf2000000000000000000000000f62f714568ee067e44ad41d8652aea9f3d8b2f3a000000000000000000000000eaf8f03f43499c2a906aeff411dec3f8cf0dc584\\\"},\\\"latest\\\"],\\\"id\\\":343,\\\"jsonrpc\\\":\\\"2.0\\\"}\",\"requestMethod\":\"POST\",\"timeout\":120000,\"url\":\"https://eth-goerli.g.alchemy.com/v2/LQg0epkAO4qxklbMgbFuiG6azP6DsBAb\"}, data=\"0x\", code=CALL_EXCEPTION, version=providers/5.6.2)\n    at Logger.makeError (/opt/indexer/node_modules/@ethersproject/logger/lib/index.js:233:21)\n    at Logger.throwError (/opt/indexer/node_modules/@ethersproject/logger/lib/index.js:242:20)\n    at checkError (/opt/indexer/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:103:16)\n    at StaticJsonRpcProvider.<anonymous> (/opt/indexer/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:687:47)\n    at step (/opt/indexer/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:48:23)\n    at Object.throw (/opt/indexer/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:29:53)\n    at rejected (/opt/indexer/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:21:65)",
			"reason": "missing revert data in call exception",
			"code": "CALL_EXCEPTION",
			"error": {
				"type": "Error",
				"message": "timeout (requestBody=\"{\\\"method\\\":\\\"eth_call\\\",\\\"params\\\":[{\\\"from\\\":\\\"0xf62f714568ee067e44ad41d8652aea9f3d8b2f3a\\\",\\\"to\\\":\\\"0x35e3cb6b317690d662160d5d02a5b364578f62c9\\\",\\\"data\\\":\\\"0xb6363cf2000000000000000000000000f62f714568ee067e44ad41d8652aea9f3d8b2f3a000000000000000000000000eaf8f03f43499c2a906aeff411dec3f8cf0dc584\\\"},\\\"latest\\\"],\\\"id\\\":343,\\\"jsonrpc\\\":\\\"2.0\\\"}\", requestMethod=\"POST\", timeout=120000, url=\"https://eth-goerli.g.alchemy.com/v2/LQg0epkAO4qxklbMgbFuiG6azP6DsBAb\", code=TIMEOUT, version=web/5.6.0)",
				"stack": "Error: timeout (requestBody=\"{\\\"method\\\":\\\"eth_call\\\",\\\"params\\\":[{\\\"from\\\":\\\"0xf62f714568ee067e44ad41d8652aea9f3d8b2f3a\\\",\\\"to\\\":\\\"0x35e3cb6b317690d662160d5d02a5b364578f62c9\\\",\\\"data\\\":\\\"0xb6363cf2000000000000000000000000f62f714568ee067e44ad41d8652aea9f3d8b2f3a000000000000000000000000eaf8f03f43499c2a906aeff411dec3f8cf0dc584\\\"},\\\"latest\\\"],\\\"id\\\":343,\\\"jsonrpc\\\":\\\"2.0\\\"}\", requestMethod=\"POST\", timeout=120000, url=\"https://eth-goerli.g.alchemy.com/v2/LQg0epkAO4qxklbMgbFuiG6azP6DsBAb\", code=TIMEOUT, version=web/5.6.0)\n    at Logger.makeError (/opt/indexer/node_modules/@ethersproject/logger/lib/index.js:233:21)\n    at Timeout._onTimeout (/opt/indexer/node_modules/@ethersproject/web/lib/index.js:179:35)\n    at listOnTimeout (node:internal/timers:559:17)\n    at processTimers (node:internal/timers:502:7)",
				"reason": "timeout",
				"code": "TIMEOUT",
				"requestBody": "{\"method\":\"eth_call\",\"params\":[{\"from\":\"0xf62f714568ee067e44ad41d8652aea9f3d8b2f3a\",\"to\":\"0x35e3cb6b317690d662160d5d02a5b364578f62c9\",\"data\":\"0xb6363cf2000000000000000000000000f62f714568ee067e44ad41d8652aea9f3d8b2f3a000000000000000000000000eaf8f03f43499c2a906aeff411dec3f8cf0dc584\"},\"latest\"],\"id\":343,\"jsonrpc\":\"2.0\"}",
				"requestMethod": "POST",
				"timeout": 120000,
				"url": "https://eth-goerli.g.alchemy.com/v2/LQg0epkAO4qxklbMgbFuiG6azP6DsBAb"
			},
			"data": "0x"
		}
	},
	"isOperator": true,
	"msg": "Failed to check operator status for indexer, assuming it has not changed"
}

The versions of docker environment are as follows:
`
graphprotocol/graph-node:v0.27.0
ghcr.io/graphprotocol/indexer-service:v0.20.1
ghcr.io/graphprotocol/indexer-agent:v0.20.2

`

**Comment by fordN** [comment]
Closing this as it's old and likely outdated. Please submit another issue if you run into it again, or comment here and we can reopen.
