### ISSUE TITLE
Problem to add template

### ISSUE THREAD

**Issue by royla22** [graphprotocol/indexer#478]
Hi,

I have a problem when i add dinamyc template in thegraph. i have this error.
![187925428-909d4f01-0361-43a3-a4af-9bd94d864dc6](https://user-images.githubusercontent.com/112970329/188693280-093c86d0-feae-4129-93dc-9338260f2ae8.png)
Please i need help

Thank you very much

regards

**Comment by hopeyen** [comment]
Not relevant here, please seek help in thegraph discord channel, suggesting the #subgraph-development channel.
