### ISSUE TITLE
Installation is failing, wrong reference to agora plugin  

### ISSUE THREAD

**Issue by oleksandrmarkelov** [graphprotocol/indexer#489]
The installation of indexer fails with:

sudo npm install -g @graphprotocol/indexer-service

npm WARN Conflicting peer dependency: graphql@15.8.0
npm WARN node_modules/graphql
npm WARN   peer graphql@"^14.7.0 || ^15.3.0" from express-graphql@0.12.0
npm WARN   node_modules/@graphprotocol/indexer-service/node_modules/express-graphql
npm WARN     express-graphql@"0.12.0" from @graphprotocol/indexer-service@0.20.4
npm WARN     node_modules/@graphprotocol/indexer-service
npm WARN ERESOLVE overriding peer dependency
npm WARN deprecated fastify-warning@0.2.0: This module renamed to process-warning
npm WARN deprecated pino-multi-stream@6.0.0: No longer supported. Use the multi-stream support in the latest core Pino
npm WARN deprecated subscriptions-transport-ws@0.11.0: The `subscriptions-transport-ws` package is no longer maintained. We recommend you use `graphql-ws` instead. For help migrating Apollo software to `graphql-ws`, see https://www.apollographql.com/docs/apollo-server/data/subscriptions/#switching-from-subscriptions-transport-ws    For general help using `graphql-ws`, see https://github.com/enisdenjo/graphql-ws/blob/master/README.md
npm ERR! code 101
npm ERR! path /usr/lib/node_modules/@graphprotocol/indexer-service/node_modules/@graphprotocol/cost-model
npm ERR! command failed
npm ERR! command sh -c -- node-pre-gyp install --fallback-to-build=false --update-binary || yarn build-release
npm ERR! response status 404 Not Found on https://github.com/graphprotocol/agora/releases/download/v0.1.14/graphprotocol-agora-plugin-v0.1.14-node-v108-linux-x64.tar.gz
npm ERR! yarn run v1.22.19
npm ERR! $ yarn build --release
npm ERR! $ cargo-cp-artifact -a cdylib node_plugin ./native/index.node -- cargo build --message-format=json-render-diagnostics --release
npm ERR! info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
npm ERR! info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@1.0.9
npm ERR! node-pre-gyp info using node@18.6.0 | linux | x64
npm ERR! node-pre-gyp http GET https://github.com/graphprotocol/agora/releases/download/v0.1.14/graphprotocol-agora-plugin-v0.1.14-node-v108-linux-x64.tar.gz
npm ERR! node-pre-gyp ERR! install response status 404 Not Found on https://github.com/graphprotocol/agora/releases/download/v0.1.14/graphprotocol-agora-plugin-v0.1.14-node-v108-linux-x64.tar.gz
npm ERR! node-pre-gyp ERR! install error
npm ERR! node-pre-gyp ERR! stack Error: response status 404 Not Found on https://github.com/graphprotocol/agora/releases/download/v0.1.14/graphprotocol-agora-plugin-v0.1.14-node-v108-linux-x64.tar.gz
npm ERR! node-pre-gyp ERR! stack     at /usr/lib/node_modules/@graphprotocol/indexer-service/node_modules/@mapbox/node-pre-gyp/lib/install.js:67:15
npm ERR! node-pre-gyp ERR! stack     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
npm ERR! node-pre-gyp ERR! System Linux 5.4.0-126-generic
npm ERR! node-pre-gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/@graphprotocol/indexer-service/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build=false" "--update-binary"
npm ERR! node-pre-gyp ERR! cwd /usr/lib/node_modules/@graphprotocol/indexer-service/node_modules/@graphprotocol/cost-model
npm ERR! node-pre-gyp ERR! node -v v18.6.0
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v1.0.9
npm ERR! node-pre-gyp ERR! not ok
npm ERR! error: failed to get `cost-model` as a dependency of package `cost-model-node-plugin v0.1.0 (/usr/lib/node_modules/@graphprotocol/indexer-service/node_modules/@graphprotocol/cost-model)`
npm ERR!
npm ERR! Caused by:
npm ERR!   failed to load source for dependency `cost-model`
npm ERR!
npm ERR! Caused by:
npm ERR!   Unable to update /usr/lib/node_modules/@graphprotocol/indexer-service/node_modules/@graphprotocol/lang
npm ERR!
npm ERR! Caused by:
npm ERR!   failed to read `/usr/lib/node_modules/@graphprotocol/indexer-service/node_modules/@graphprotocol/lang/Cargo.toml`
npm ERR!
npm ERR! Caused by:
npm ERR!   No such file or directory (os error 2)
npm ERR! Did not copy "cdylib:node_plugin"
npm ERR! error Command failed with exit code 101.
npm ERR! error Command failed with exit code 101.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-10-02T21_15_11_547Z-debug-0.log

**Comment by soleinik-figment** [comment]
Same issue here 

`npm install -g @graphprotocol/indexer-cli@0.19.3
npm WARN deprecated fastify-warning@0.2.0: This module renamed to process-warning
npm WARN deprecated pino-multi-stream@6.0.0: No longer supported. Use the multi-stream support in the latest core Pino
npm ERR! code 1
npm ERR! path /usr/local/lib/node_modules/@graphprotocol/indexer-cli/node_modules/@graphprotocol/cost-model
npm ERR! command failed
npm ERR! command sh -c -- node-pre-gyp install --fallback-to-build=false --update-binary || yarn build-release
npm ERR! response status 404 Not Found on https://github.com/graphprotocol/agora/releases/download/v0.1.14/graphprotocol-agora-plugin-v0.1.14-node-v108-linux-x64.tar.gz
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@1.0.9
npm ERR! node-pre-gyp info using node@18.7.0 | linux | x64
npm ERR! node-pre-gyp http GET https://github.com/graphprotocol/agora/releases/download/v0.1.14/graphprotocol-agora-plugin-v0.1.14-node-v108-linux-x64.tar.gz
npm ERR! node-pre-gyp ERR! install response status 404 Not Found on https://github.com/graphprotocol/agora/releases/download/v0.1.14/graphprotocol-agora-plugin-v0.1.14-node-v108-linux-x64.tar.gz 
npm ERR! node-pre-gyp ERR! install error 
npm ERR! node-pre-gyp ERR! stack Error: response status 404 Not Found on https://github.com/graphprotocol/agora/releases/download/v0.1.14/graphprotocol-agora-plugin-v0.1.14-node-v108-linux-x64.tar.gz
npm ERR! node-pre-gyp ERR! stack     at /usr/local/lib/node_modules/@graphprotocol/indexer-cli/node_modules/@mapbox/node-pre-gyp/lib/install.js:67:15
npm ERR! node-pre-gyp ERR! stack     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
npm ERR! node-pre-gyp ERR! System Linux 5.14.0-1052-oem
npm ERR! node-pre-gyp ERR! command "/usr/bin/node" "/usr/local/lib/node_modules/@graphprotocol/indexer-cli/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build=false" "--update-binary"
npm ERR! node-pre-gyp ERR! cwd /usr/local/lib/node_modules/@graphprotocol/indexer-cli/node_modules/@graphprotocol/cost-model
npm ERR! node-pre-gyp ERR! node -v v18.7.0
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v1.0.9
npm ERR! node-pre-gyp ERR! not ok 
npm ERR! ERROR: [Errno 2] No such file or directory: 'build-release'
`

**Comment by fordN** [comment]
@oleksandrmarkelov @soleinik-figment it appears you are both using Node v18 on these machines?  The pre-built agora binaries do not yet include one for Node v18.  The build process falls back to compiling the agora binary on your machine  if the binary download fails, I'll make a task to look into why that is failing on your machines. 

In the meantime, I'd recommend using the LTS Node version, currently `16.17.1`, https://nodejs.org/en/download/, for which there is a prebuilt binary (https://github.com/graphprotocol/agora/releases/tag/v0.1.14).

**Comment by oleksandrmarkelov** [comment]
Actually using 16.17.1 results in error when starting the indexer, need to downgrade to 14

TypeError: this.splice is not a function
    at HeadersList.append (/home/graphval/.nvm/versions/node/v16.17.1/lib/node_modules/@graphprotocol/indexer-service/node_modules/cross-undici-fetch/dist/patch-headers-list.js:44:16)
    at Headers.append (/home/graphval/.nvm/versions/node/v16.17.1/lib/node_modules/@graphprotocol/indexer-service/node_modules/undici/lib/fetch/headers.js:239:31)
    at fill (/home/graphval/.nvm/versions/node/v16.17.1/lib/node_modules/@graphprotocol/indexer-service/node_modules/undici/lib/fetch/headers.js:56:15)
    at new Headers (/home/graphval/.nvm/versions/node/v16.17.1/lib/node_modules/@graphprotocol/indexer-service/node_modules/undici/lib/fetch/headers.js:180:7)
    at new Request (/home/graphval/.nvm/versions/node/v16.17.1/lib/node_modules/@graphprotocol/indexer-service/node_modules/cross-undici-fetch/dist/create-node-ponyfill.js:78:29)
    at Object.fetch (/home/graphval/.nvm/versions/node/v16.17.1/lib/node_modules/@graphprotocol/indexer-service/node_modules/cross-undici-fetch/dist/create-node-ponyfill.js:110:24)
    at defaultAsyncFetch (/home/graphval/.nvm/versions/node/v16.17.1/lib/node_modules/@graphprotocol/indexer-service/node_modules/@graphql-tools/url-loader/index.js:43:29)
    at /home/graphval/.nvm/versions/node/v16.17.1/lib/node_modules/@graphprotocol/indexer-service/node_modules/@graphql-tools/url-loader/index.js:479:36
    at new ValueOrPromise (/home/graphval/.nvm/versions/node/v16.17.1/lib/node_modules/@graphprotocol/indexer-service/node_modules/value-or-promise/build/main/ValueOrPromise.js:14:21)
    at executor (/home/graphval/.nvm/versions/node/v16.17.1/lib/node_modules/@graphprotocol/indexer-service/node_modules/@graphql-tools/url-loader/index.js:447:20)

**Comment by soleinik-figment** [comment]
installing 
```
npm install --silent --unsafe -g @graphprotocol/indexer-cli@0.19.3
```
of node:lts-bullseye (v16.17.1) image worked for me

**Comment by fordN** [comment]
Closing since this is a bit stale. I'll reopen if issue pops back up.
