### ISSUE TITLE
Really bad UX for displaying actions

### ISSUE THREAD

**Issue by kaiwetlesen** [graphprotocol/indexer#516]
The user experience for displaying actions is unusable. Unless an indexer has an ultra-wide display and eagle vision, it is not possible to see the entirety of the displayed data. Furthermore, attempts to massage the display output are thwarted due to the use of Chalk, which throws random escape characters and colour change sequences into the output. Please consider removing Chalk from all output unless _absolutely neccessary_ for highlighting errors or similar.
![image](https://user-images.githubusercontent.com/9599381/196545230-3c31c7c0-84b9-4eef-8b89-c5544adaae96.png)

**Comment by timfong888** [comment]
@kaiwetlesen You prefer things to be via CLI vs Browser? Or would a browser with the select options also be valuable?

**Comment by kaiwetlesen** [comment]
Personally? I’ve always preferred a decent command line interface as they always seem quicker.On May 5, 2023, at 12:02, timfong888 ***@***.***> wrote:﻿
@kaiwetlesen You prefer things to be via CLI vs Browser? Or would a browser with the select options also be valuable?
