### ISSUE TITLE
Store error: database unavailable

### ISSUE THREAD

**Issue by enzoferey** [graphprotocol/indexer#534]
Hi !

Not sure if this is the correct repo, if not, please let me know where I should report this issue.

We are running a subgraph on Polygon mainnet (https://thegraph.com/hosted-service/subgraph/enzoferey/zomon-subgraph) via the hosted service and we are randomly getting `[GraphQL] Store error: database unavailable` errors.

Is there any reason for doing so ?

**Comment by fordN** [comment]
Hey @enzoferey 👋 

This repo is for software that indexers on The Graph network run to register on and interact with the decentralized network. There is another repo, https://github.com/graphprotocol/support/issues, for hosted-service issues. 

However, I can speak a bit to the issue you reported.  The `database unavailable` error indicates the DB went under maintenance or was not available and is typically a temporary error that will be resolved when the subgraph is restarted and starts syncing again.  It looks like [your subgraph](https://github.com/graphprotocol/support/issues) is healthy now, so its resolved now?

**Comment by fordN** [comment]
Closing this issue as it appears to be resolved. 

In the future please direct hosted-service issues to the #hosted-service channel in [The Graph discord](https://github.com/graphprotocol) or to the [hosted-service support repo](https://github.com/graphprotocol/support/issues).

**Comment by enzoferey** [comment]
Thanks for the hints @fordN 👍🏻 

I did get an answer at https://github.com/graphprotocol/graph-node/issues/4135 for future reference.
