### ISSUE TITLE
[BUG]: MIPs: indexers close allocations with the same POI per subgraph accross all closed allocations

### ISSUE THREAD

**Issue by davaymne** [graphprotocol/indexer#538]
All Indexers in MIPs close allocations with the same POI per every given subgraph accross all corresponding allocations being closed.

If you select any indexer and select any subgraph and look up their closed allocations, you will see that all allocations are being closed with the same POI per given subgraph.

For instance: 
 - https://goerli.graphscan.io/profile?id=0xe1230b5452d80b46a167fec741cacea9fda66118#indexer-allocations
 <img width="1360" alt="Screenshot 2022-11-09 at 01 17 46" src="https://user-images.githubusercontent.com/29555611/200712601-147339a6-09a0-4c57-a920-6a68c1f038d6.png">
- https://goerli.graphscan.io/profile?id=0x0f6feb3ba20c56e94cfbcd98339e99bce629d912#indexer-allocations
<img width="1315" alt="Screenshot 2022-11-09 at 01 19 03" src="https://user-images.githubusercontent.com/29555611/200712808-11b5e266-9513-464e-9240-e520a76310e1.png">

And so on...

While subgraphs is being indexed successfully without any errors.

**Comment by davaymne** [comment]
I believe the culprit is EPOCH ORACLE subgraph https://api.thegraph.com/subgraphs/name/graphprotocol/goerli-epoch-block-oracle/graphql,  which constantly returns block `24758015` on query from Agent: https://github.com/graphprotocol/indexer/blob/9d1c8f8faef1686cf8caf217d6e61bd260a496ce/packages/indexer-common/src/indexer-management/monitor.ts#L574

GraphQL query: [query](https://api.thegraph.com/subgraphs/name/graphprotocol/goerli-epoch-block-oracle/graphql?query=++++++++++query+network%7B%0A++++++++++++network%28id%3A+%22eip155%3A100%22%29+%7B%0A++++++++++++++latestValidBlockNumber+%7B%0A++++++++++++++++network+%7B%0A++++++++++++++++++id%0A++++++++++++++++%7D%0A++++++++++++++++epochNumber%0A++++++++++++++++blockNumber%0A++++++++++++++++previousBlockNumber+%7B%0A++++++++++++++++++network+%7B%0A++++++++++++++++++++id%0A++++++++++++++++++%7D%0A++++++++++++++++++epochNumber%0A++++++++++++++++++blockNumber%0A++++++++++++++++%7D%0A++++++++++++++%7D%0A++++++++++++%7D%0A++++++++++%7D)

Response:
```
{
  "data": {
    "network": {
      "latestValidBlockNumber": {
        "network": {
          "id": "eip155:100"
        },
        "epochNumber": "1253",
        "blockNumber": "24758015",
        "previousBlockNumber": {
          "network": {
            "id": "eip155:100"
          },
          "epochNumber": "1252",
          "blockNumber": "24758015"
        }
      }
    }
  }
}
```

I can confirm by query graph-node directly having 
 - block: `24758015` and 
  - hash: `0xe17674766294210a32a09550a7ec083a7c10eb2380b6a2e21017f503563350fc`
it returns  `"proofOfIndexing": "0xe090c3d1aea7d09ec8ea19f3858c095f77da1a7d270b233a2a9ed8b45b5939e5"` as per 1st screenshot above.

**Comment by hopeyen** [comment]
Hi 👋 This should be an expected behavior as all indexers closing a particular allocation during the same epoch should submit their proof of indexing at the start block number of the epoch. POI is normalized across the indexers such that they are compared deterministically.

**Comment by ivel13** [comment]
Hello,
Still cannot close allocations, and indexer-agent throws the same error but with another block number:
`[15:56:00.043] ERROR (IndexerAgent/1): Failed to query block hash
    component: "IndexingStatusFetcher"
    network: "gnosis"
    blockNumber: 24936690
    error: "Failed to query graph node for blockHashFromNumber"`
