### ISSUE TITLE
AllocationManager Failed to send transaction

### ISSUE THREAD

**Issue by grumas-rc** [graphprotocol/indexer#570]
Unable to create allocation.
When i execute `graph indexer rules set QmcdDo39c8ztsCViQ5kQotjNj4iL3QVq9tnQEqVJXffcD5 allocationAmount 505000 decisionBasis always` logs(attached below) start spamming errors.
I see transaction status fail [https://etherscan.io/tx/0x64e217215ed449b74e7b73c3864c8b7f0f0de0f802b13f55321cf4230114a4de](https://etherscan.io/tx/0x64e217215ed449b74e7b73c3864c8b7f0f0de0f802b13f55321cf4230114a4de)

indexer-agent v0.20.6 
config
    --gas-price-max 50 \
    --graph-node-query-endpoint http://mainnet-querynode.graph:8000/ \
    --graph-node-admin-endpoint http://mainnet-graphnode1.graph:8020/ \
    --graph-node-status-endpoint http://mainnet-graphnode1.graph:8030/graphql \
    --metrics-port 7300 \
    --public-indexer-url <hidden> \
    --indexer-geo-coordinates '<hidden>' '<hidden>' \
    --postgres-host mainnet-postgres-main.graph \
    --postgres-port 5432 \
    --postgres-username <hidden> \
    --postgres-password <hidden> \
    --postgres-database graph-agent \
    --ethereum-network mainnet \
    --ethereum https://eth-mainnet-rpc.local \
    --mnemonic '<hidden>' \
    --indexer-address <hidden> \
    --no-restake-rewards \
    --network-subgraph-deployment QmV614UpBCpuusv5MsismmPYu4KqLtdeNMKpiNrX56kw6u \
    --network-subgraph-endpoint https://gateway.thegraph.com/network \
    --dai-contract 0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48 \
    --collect-receipts-endpoint https://gateway.network.thegraph.com/collect-receipts \
    --epoch-subgraph-endpoint https://api.thegraph.com/subgraphs/name/graphprotocol/mainnet-epoch-block-oracle

[indexer-agent.log](https://github.com/graphprotocol/indexer/files/10284710/indexer-agent.log)

**Comment by grumas-rc** [comment]
@fordN

**Comment by fordN** [comment]
hey @grumas-rc 👋 

It looks like your transaction is stuck in the mempool.  That error message, "ALREADY_EXISTS: already known", is what a geth node (slightly older version, 1.9) returns if there is already an identical transaction in the mempool.  I'd recommend restarting the indexer-agent, since it will keep retrying based on the transaction timeout (the tx wasn't confirmed in time.)

But I'm curious, did it resolve itself? I'd expect the tx to go through even if it's a bit slow...

**Comment by grumas-rc** [comment]
I'll repeat here for the sake of posterity 😊 
Problem is not solved by itself, when indexer-agent is restarted, a new transaction is created and again the same errors in logs.
My rpc erigon version 2.31.0-stable
And if the message gets stuck in the mempool, will the transaction get into the chain? I previously sent a link to a failed transaction.

**Comment by grumas-rc** [comment]
Gas estimation error on Erigon 2.31.
Updating Erigon to version 2.32 solved the problem!
