### ISSUE TITLE
Goerli AllocationExchange deployment is not set with the correct signer

### ISSUE THREAD

**Issue by madumas** [graphprotocol/indexer#593]
The AllocationExchange contract on Goerli at `0x67fbea097202f46d601d7c937b5dbb615659adf2` has been deployed with the authority 
`0x52e498aE9B8A5eE2A5Cd26805F06A9f29A7F489F` but the testnet gateways are set to `0xe1EC4339019eC9628438F8755f847e3023e4ff9c`

Results in indexer-agent redeem transactions being reverted with `execution reverted: Exchange: invalid signer`

**Comment by fordN** [comment]
Thanks for the solution driven report! 
I've already discussed this on discord with you but for posterity I'll update here too: 

The authority mapping on the Goerli AllocationExchange contract has been updated to include `0xe1EC4339019eC9628438F8755f847e3023e4ff9c` and voucher redeem transactions are working well now.
