### ISSUE TITLE
indexer-agent  --allocation-exchange-contract parameter is ignored

### ISSUE THREAD

**Issue by madumas** [graphprotocol/indexer#594]
Setting `--allocation-exchange-contract` or `INDEXER_AGENT_ALLOCATION_EXCHANGE_CONTRACT` to a different address is ignored.

Expected result:
Address specified is used for redeem transactions

Result:
Uses the default address for the network

**Comment by hopeyen** [comment]
Hi there 👋 
The argument `--allocation-exchange-contract` seems to be removed and it is now sourced from the network contracts, I think the implementation is [here](https://github.com/graphprotocol/indexer/blob/main/packages/indexer-agent/src/commands/start.ts#L647).
This might've been confusing, but the argument no longer need to be provided and I think we should just remove it 🤔 . 
Did you need to provide a different address? may I ask why?

**Comment by madumas** [comment]
I was trying to gather more information for issue #593 by using an alternate AllocationExchange contract on the testnet

**Comment by hopeyen** [comment]
Ah okay, makes sense, thanks! Will flag the issue for contract address updates

**Comment by fordN** [comment]
@hopeyen can you update indexer-agent to fully remove the allocation-exchange-contract startup parameter since it is no longer used?
