### ISSUE TITLE
Request network.md on arbitrum network

### ISSUE THREAD

**Issue by suntzu93** [graphprotocol/indexer#622]
Hello,
I'm looking info to config indexer on arbitrum network but seem like we don't have network.md for arbitrum yet. 

Can the team create a file network.md for arbitrum network ?

**Comment by suntzu93** [comment]
@neysofu I think you can help.

**Comment by saihaj** [comment]
I think this is taken care 
- https://github.com/graphprotocol/indexer/blob/main/docs/networks/arbitrum-goerli.md
- https://github.com/graphprotocol/indexer/blob/main/docs/networks/arbitrum-one.md
- https://github.com/graphprotocol/indexer/blob/main/docs/networks/arbitrum-sepolia.md
