### ISSUE TITLE
Metrics ?

### ISSUE THREAD

**Issue by Amxx** [graphprotocol/indexer#65]
https://github.com/graphprotocol/mission-control-indexer/blob/master/k8s/base/indexer-agent/deployment.yaml implies that the indexer-agent container has a `/metrics` endpoint available on port 7300 for prometheus. I'm not able to reach it, and it is not documented.
Is there a flag to enable it / change the port ?

**Comment by fordN** [comment]
This was likely solved elsewhere; in case anyone else comes across the issue: the `--metrics-port` (default `7300`) startup parameter can be used to update the port where the indexer-agent serves prometheus metrics.
