### ISSUE TITLE
Review if the GraphNode class needs an array of index node ids

### ISSUE THREAD

**Issue by tilacog** [graphprotocol/indexer#714]
In light of this Graph Node PR: https://github.com/graphprotocol/graph-node/pull/4695, we might be able to remove the need for the index node ids arguments, as Graph Node might be capable of handling assignments without that piece of information. 

Currently affected LOC:

1. https://github.com/graphprotocol/indexer/blob/1fde62600c2cd37cf0a71a0006009b4a0261a460/packages/indexer-common/src/indexer-management/allocations.ts#L297

2. https://github.com/graphprotocol/indexer/blob/1fde62600c2cd37cf0a71a0006009b4a0261a460/packages/indexer-common/src/indexer-management/client.ts#L513

3. https://github.com/graphprotocol/indexer/blob/1fde62600c2cd37cf0a71a0006009b4a0261a460/packages/indexer-common/src/indexer-management/resolvers/allocations.ts#L449

**Comment by fordN** [comment]
Resolved in https://github.com/graphprotocol/indexer/pull/868
