### ISSUE TITLE
Update README files

### ISSUE THREAD

**Issue by tilacog** [graphprotocol/indexer#743]
Most `README.md` files are outdated and no longer match the available command line options and arguments. 

- **Indexer-Agent**: [README](https://github.com/graphprotocol/indexer/blob/main/packages/indexer-agent/README.md) vs CLI structure ([single-network](https://github.com/graphprotocol/indexer/blob/main/packages/indexer-agent/src/commands/start.ts), [multi-network](https://github.com/graphprotocol/indexer/blob/main/packages/indexer-agent/src/commands/start-multi-network.ts), [shared](https://github.com/graphprotocol/indexer/blob/main/packages/indexer-agent/src/commands/common-options.ts))
- **Indexer-Service**: [README](https://github.com/graphprotocol/indexer/blob/main/packages/indexer-service/README.md) vs [CLI structure](https://github.com/graphprotocol/indexer/blob/93694eeb2cea19abebee0e547b8ad992c6b462dd/packages/indexer-service/src/commands/start.ts#L41-L178)
- **Indexer-CLI**: [README](https://github.com/graphprotocol/indexer/blob/main/packages/indexer-cli/README.md) vs [CLI (module-based) structure](https://github.com/graphprotocol/indexer/tree/main/packages/indexer-cli/src/commands)

**Comment by nikhilverma360** [comment]
Hi @tilacog 👋,
I am interested in this issue, can you assign me?

**Comment by tilacog** [comment]
Thanks @nikhilverma360!
Let me know if you have any questions!
