### ISSUE TITLE
Feature Request: Check for pending Transactions blocking the nonce when broadcasting new ones

### ISSUE THREAD

**Issue by tilacog** [graphprotocol/indexer#751]
The Agent occasionally fails to broadcast a transaction, possibly due to a prior transaction blocking the nonce. 

We address this by manually sending a mock transaction to advance the nonce, allowing the Agent's transaction manager to pick it up when broadcasting a new transaction.

One solution is to shift to stateful transaction management, where the Agent maintains the last nonce (in the database or memory), ensuring quicker access instead of relying on the RPC provider for nonce information.

**Comment by fordN** [comment]
I haven't seen issues like this for very long time. Closing until/unless it resurfaces.
