### ISSUE TITLE
wrong url in indexer/blob/main/docs/networks/arbitrum-one.md

### ISSUE THREAD

**Issue by matthewdarwin** [graphprotocol/indexer#757]
From: https://discord.com/channels/438038660412342282/791444480628490290/1146432829111144539

The URL https://gateway.network.thegraph.com/ is incorrect.  "network" should be removed.

Please check all URLs of this form and make sure they are corrected.

**Comment by matthewdarwin** [comment]
Also https://github.com/graphprotocol/indexer/blob/v0.20.22/docs/networks/ethereum-mainnet.md

**Comment by mujtabaidrees94** [comment]
For Arbitrum the gateway URL should be:  https://gateway-arbitrum.network.thegraph.com/

**Comment by fordN** [comment]
Resolved by https://github.com/graphprotocol/indexer/pull/953
