### ISSUE TITLE
indexer-agent: maxAllocationEpochs not being considered when identifiyng expired allocations

### ISSUE THREAD

**Issue by tilacog** [graphprotocol/indexer#760]
Multiple indexers have reported that the Indexer Agent will close and renew allocations one epoch after creation. 

This means that the `maxAllocationEpochs` value provided by the Staking contract is not being considered when identifying expired allocations during the reconciliation loop.

```[tasklist]
### Requirements
- [x] The Agent must only close allocations when they are duly expired.
- [x] For a better indexer experience, add logs that inform how the allocation expiration epoch was calculated: either by an indexing rule, the `maxAllocationEpoch` value obtained from the Staking contract, or the minimum default of one epoch.
```

```[tasklist]
### Success Criteria
- [x] **Manual Test**: Confirm (on-chain) that allocations are closed `N` epochs after creation, where `N` is the expected value for `maxAllocationEpochs`. _(considering governing indexing rules have no value set for `allocationLifetime`)_
```

**Comment by tilacog** [comment]
After a thorough review of user feedback suggesting a potential bug, we've found evidence indicating that the Agent is functioning as intended.

Logs show that `maxAllocationEpochs` value is being correctly fetched from the Staking contracts and being considered in the desired allocation lifetime calculation as designed.

**Comment by fordN** [comment]
Closing this issue. See comment above for explanation.
