### ISSUE TITLE
Report of Indexer CLI returning incorrect endpoint status on Arbitrum One network

### ISSUE THREAD

**Issue by alex-pakalniskis** [graphprotocol/indexer#777]
Indexer reports the Indexer CLI returns incorrect endpoint status on Arbitrum One network

From [Slack](https://graphprotocol.slack.com/archives/C032EE2915F/p1694909597481909):

> `graph indexer status --network=arbitrum-one` returns `down` endpoints even though the endpoints are up
> i just spent my weekend debugging someone's issue that wasn't even an issue in the first place lol
> Now they're getting endpoints `up` without changing anything in their setup lol
> -Payne

![Image](https://user-images.githubusercontent.com/43630382/268674450-14d95de6-60d3-469e-82ad-a200e1468aea.png)

> ok so on my side, having 1300+ subgraphs in my database, it takes like 5 minutes to get that command to show anything - so I wonder if that contributed to the endpoints being down part
> and on the other hand, that guy haven't had his operator wallet set, so in that case, is it a bug, or a feature -Payne

> o ok, so it's probably failing early in the endpoint checking process because they don't have an operator wallet set.  Worth looking into 
> The status command needs an overhaul in my opinion.  The output is unreadable if you have a bunch of deployments
> Should probably just be summaries with counts of types of deployments or separate out deployment statuses into a different subcommand
> -Ford

> I think separate commands would be ideal
> -Payne

> also once the graphman commands are integrated into the graph-node graphql API then the indexer-cli can use them to get more details and manage subgraphs.  Could use that to have a nice indexer deployments CLI module for managing deployments
> with commands for status, rewinding, reassigning, etc...
> -Ford

> yes pls
> -Payne

**Comment by fordN** [comment]
I haven't been able to reproduce this issue. Closing until we receive further confirmation and details.
