### ISSUE TITLE
Add a configuration option to prevent allocation to lagging subgraphs

### ISSUE THREAD

**Issue by tilacog** [graphprotocol/indexer#786]
We suggest introducing an `INDEXER_AGENT_ALLOCATION_MAX_BLOCKS_BEHIND` flag to let indexers set a block threshold to prevent creating allocations to deployments lagging beyond a certain distance from the chain head.

### Proposed Implementation
1. Introduce a new configuration flag, `INDEXER_AGENT_ALLOCATION_MAX_BLOCKS_BEHIND` in the Indexer Agent.
2. Before allocation, the Indexer Agent checks the number of blocks a subgraph deployment is behind the chain head.
3. If the deployment is behind more than the specified number in `INDEXER_AGENT_ALLOCATION_BLOCKS_BEHIND`, the Agent will skip allocating to that particular subgraph.

### Benefits
- Reduces risk of allocating towards invalid subgraph deployments.
- Simplifies the process of providing a list of subgraphs, alleviating concerns about the sync status of individual deployments.

**Comment by fordN** [comment]
I'm not sure this is viable, given we'd have to wait for deployments to be synced close to chain head before allocating.  Right now that would be departure from behavior of most indexers.  Closing for now, if this featured is wanted it should resurface.
