### ISSUE TITLE
`indexer-agent` can allocate to subgraphs that it can't deploy

### ISSUE THREAD

**Issue by alex-pakalniskis** [graphprotocol/indexer#790]
## Overview

`indexer-agent` can allocate to subgraphs that it can't deploy. Furthermore, there are no checks before sending the transaction and no warning in the `indexer-cli`

### Payne's example
 
> so if a sub is grafted it allocates to the top-most graft, not even having the rest locally, and that graft doesn't even deploy yet you're allocated
> and you find out end of the month
> and you're totally fucked
> 💀

**Comment by alex-pakalniskis** [comment]
@fordN any updates on this? I think you mentioned you'd chat with Payne about it.

**Comment by fordN** [comment]
I believe this is resolved, closing.
