### ISSUE TITLE
Enable selectable freshness checking on subgraph queries

### ISSUE THREAD

**Issue by alex-pakalniskis** [graphprotocol/indexer#802]
## Current behavior

* The freshness "check and wait" behavior is applied globally to all subgraph queries even when unnecessary. 
    * Epoch Block Oracle subgraph doesn't need to be up to chainhead as long as data is available for the current epoch
    * Quick validation checks for Indexer CLI do not need this freshness check either

## Preferred behavior

* The freshness "check and wait" behavior is applied only as necessary to relevant subgraph queries and not as a global check on all queries

**Comment by fordN** [comment]
This is done. There is a checkedQuery() function which checks freshness and query() which does not.
