### ISSUE TITLE
Running a subgraph and hitting rate limits.

### ISSUE THREAD

**Issue by Logic-Beach** [graphprotocol/indexer#834]
Hi team, I am running an indexer which grabs the latest block number, then hits my RPC with an `eth_getTransactionReceipt` request for every tx in the block. This is causing a bunch of 429 errors since the 1000s of requests hit the RPC all at once. Is there any way around this?

**Comment by matthewdarwin** [comment]
Graph-node will slow down when it gets a 429 response.

The solution to do fast indexing is to run your own RPC node. Or use firehose.

**Comment by fordN** [comment]
Graph-node now supports fetching all receipts in a single request using `eth_getBlockReceipts` (https://github.com/graphprotocol/graph-node/pull/5341).  That should help with the request volume.
