### ISSUE TITLE
Allow allocations to be closed to get query fees but not indexing rewards

### ISSUE THREAD

**Issue by matthewdarwin** [graphprotocol/indexer#836]
Currently there's no way to close allocations via the agent/cli for networks unsupported by indexing rewards.  With the upgrade indexer now there is queries on networks where there is no indexing fees, so need to able to claim query fees

![image](https://github.com/graphprotocol/indexer/assets/26171839/ba917d67-ce8f-440e-aebf-33815f009583)

**Comment by jhjhjh94** [comment]
`graph indexer allocations close arbitrum-one <allocation id> 0x0000000000000000000000000000000000000000000000000000000000000000 --force`

action queue won't work, have to close independently

**Comment by fordN** [comment]
This one _should_ be resolved in #949
