### ISSUE TITLE
v0.21.1 crash looping on docker

### ISSUE THREAD

**Issue by kw1knode** [graphprotocol/indexer#845]
No logs to report, container not able to start.

**Comment by fordN** [comment]
Both `indexer-service` and `indexer-agent`?

**Comment by kw1knode** [comment]
> Both `indexer-service` and `indexer-agent`?

I only had issues with service, but some reports of both.

**Comment by fordN** [comment]
Ok, that's what I'm seeing too. I'm able to reproduce on `indexer-service`; I'm getting an odd `segfault` error that doesn't produce any logs. 

I'm bisecting back through git commit history to identify the issue now.

**Comment by madnadyka** [comment]
Hello! Have same issue with `indexer-service`, network arbitrum-sepolia

**Comment by lincolncpp** [comment]
Same issue with `indexer-service`:
- Docker container exited without logs
- `segfault` when running from npm packages (`@graphprotocol/indexer-service@0.21.1`)
- `segfault` when running from source (branch `main`)

**Comment by rafael-protofire** [comment]
same issue here with `indexer-service`.
