### ISSUE TITLE
Make max block distance default to a higher value

### ISSUE THREAD

**Issue by trader-payne** [graphprotocol/indexer#856]
Right now, the `INDEXER_AGENT_SUBGRAPH_MAX_BLOCK_DISTANCE` is defaulting to 0, which breaks things completely.

This default needs to be bumped to a higher value, say `1000`  which is ~3-4min in the arbitrum world.

**Comment by matthewdarwin** [comment]
1000 is probably a bit too big for bitcoin?

**Comment by fordN** [comment]
Resolved in https://github.com/graphprotocol/indexer/pull/955
