### ISSUE TITLE
Unable to collect receipts above 25000 for query fee voucher

### ISSUE THREAD

**Issue by jhjhjh94** [graphprotocol/indexer#860]
> "msg":"Too many receipts to collect in oneshot, collecting in batches of '25000 receipts"}

> "cause":{"message":"Request failed with status code 413","stack":"Error: Request failed with status code 413

> "config":{"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false},"transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/octet-stream","User-Agent":"axios/0.26.1","Content-Length":2800020},"method":"post","url":"https://gateway-arbitrum.network.thegraph.com/partial-voucher","data":{}},"status":413}},"msg":"Failed to collect receipts in exchange for an on-chain query fee voucher"}

> client intended to send too large body: 2800020 bytes, request: "POST /partial-voucher HTTP/1.1"

Increasing client_max_body_size should be able to solve this

**Comment by abarmat** [comment]
Thanks for reporting, this was a configuration issue on the ingress of the gateway. The ingress configuration has been updated to fix this issue and we tried again and now works. I'll close this.
