### ISSUE TITLE
graph indexer status stuck

### ISSUE THREAD

**Issue by upnodedev** [graphprotocol/indexer#873]
I have tried to upgrade to the version [v0.21.2](https://github.com/graphprotocol/indexer/releases/tag/v0.21.2)

And when I run `graph indexer status --network arbitrum-one` it freezes without any error!

It seems to be Freshness checking problem

```
{"level":40,"time":1711988273553,"pid":1,"hostname":"cc48121a1840","name":"IndexerAgent","component":"Network","indexer":"0xc9014686F6336Ad558B539565D5DfF840b339082","protocolNetwork":"eip155:42161","component":"FreshnessChecker","latestIndexedBlock":196521567,"latestNetworkBlock":196521591,"blockDistance":24,"freshnessThreshold":0,"subgraph":"Network Subgraph","retriesLeft":null,"msg":"Network Subgraph is not fresh. Sleeping for 5000 ms before retrying"}
```

**Comment by fordN** [comment]
Hey @upnodedev the default value for maxBlockDistance (how far behind the agent will let the network subgraph get before pausing operations) is set too low. I'm creating a PR to update the default now, but you can also set a higher number in your configs to get past those subgraph freshness blocking issues.

**Comment by fordN** [comment]
See [docs](https://github.com/graphprotocol/indexer/blob/main/docs/subgraph-freshness.md) for reference.

**Comment by fordN** [comment]
Here's the PR to improve default values: https://github.com/graphprotocol/indexer/pull/955.

Closing this issue now, happy to reopen if you continue to have problems.
