### ISSUE TITLE
Indexer-agent cannot close an allocation for an unsupported network

### ISSUE THREAD

**Issue by madumas** [graphprotocol/indexer#894]
Closing an allocation for a network that isn't officially supported by the network results in an error. Here for `bsc`:

{"level":20,"time":1715351792424,"pid":1,"hostname":"indexer-agent-6cdd4d69df-d88q7","name":"IndexerAgent","component":"ActionManager","function":"executeApprovedActions","protocolNetwork":"eip155:42161","results":[{"actionID":3672,"failureReason":"Failed to prepare tx call data: Failed to resolve CAIP2 ID from the provided network alias: bsc","protocolNetwork":"eip155:42161"}],"msg":"Completed batch action execution"}

This appears to be caused by the method `Caip2ByChainAlias` that uses hardcoded mappings. This is problematic because with sunrise, indexers are expected to create allocations for unsupported networks, and handle queries for them. Without the ability of closing the allocations, indexers cannot collect query fees.

**Comment by jhjhjh94** [comment]
Ref : https://github.com/graphprotocol/indexer/issues/836
