### ISSUE TITLE
Failed to resolve CAIP2 ID from the provided network alias: base

### ISSUE THREAD

**Issue by suntzu93** [graphprotocol/indexer#915]
The network now supports rewards for 4 new chains(base, bsc , linea , scroll), but the indexer agent hasn't updated these chains yet. So, when closing the allocation, it throws an error: 'Failed to resolve CAIP2 ID from the provided network alias: base'

**Comment by matthewdarwin** [comment]
See also https://github.com/graphprotocol/indexer/issues/905
