### ISSUE TITLE
Completely remove reliance on hosted-service subgraphs

### ISSUE THREAD

**Issue by fordN** [graphprotocol/indexer#923]
## Background
Tests are still querying hosted-service subgraphs. Docs still reference hosted-service subgraphs and suggest indexers rely on them.
```[tasklist]
### Tasks
- [ ] Remove hosted-service subgraph references from docs
- [x] Do not rely on hosted-service subgraph queries in tests
```

**Comment by alex-pakalniskis** [comment]
Docs updates PR: https://github.com/graphprotocol/indexer/pull/924

**Comment by dwerner** [comment]
For now we've handled the code changes in https://github.com/graphprotocol/indexer/pull/904, still need to update the readmes.
