### ISSUE TITLE
Enable Indexers to assign `graph-node` deployment rules to initial subgraph deployments

### ISSUE THREAD

**Issue by alex-pakalniskis** [graphprotocol/indexer#928]
> Give control of initial deployments to `graph-node`'s deployment rules
Qualify of life request from Vincent T. | Data Nexus during IOH
![image](https://github.com/graphprotocol/indexer/assets/43630382/88b7759d-0624-418f-9648-b61a9783e730)

**Comment by fordN** [comment]
Resolved in https://github.com/graphprotocol/indexer/pull/868
