### ISSUE TITLE
Add support for Fuse subgraphs

### ISSUE THREAD

**Issue by bleiva** [graphprotocol/indexer#945]
We already opened some allocations to support Fuse subgraphs but we are getting an error when we want to close these allocations. Is it possible to add support to close them both without getting error and without getting rewards (If I'm not wrong this network is not already supported for rewards right?)

`
"failureReason": "Failed to prepare tx call data: Failed to resolve CAIP2 ID from the provided network alias: fuse"
`

Maybe this PR is related:

https://github.com/graphprotocol/indexer/pull/939/commits/25854480617e26cbc42ecaf19dfddb671f6ef8f5

Thank you

**Comment by fordN** [comment]
Hey @bleiva thanks for reporting. This should be resolved with https://github.com/graphprotocol/indexer/pull/949.
